# Generated by Django 5.1.4 on 2025-01-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_theater_date_alter_theater_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='theater',
            new_name='theaters',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='theater',
            new_name='theaters',
        ),
    ]
