# Generated by Django 5.1.4 on 2025-01-26 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_theater_booking_theaters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('Royal Sofa', 380), ('Royal Gold', 330), ('Royal Silver', 300)], default=datetime.date(2025, 1, 25), max_length=20),
            preserve_default=False,
        ),
    ]
