# Generated by Django 5.1.4 on 2025-02-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_theater_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='theater',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
    ]
